name: azkar_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'

dependencies:
  al_quran: ^0.1.1+5
  animations: ^2.0.11
  audioplayers: ^6.1.0
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  collection: ^1.17.1
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.6
  device_preview: ^1.2.0
  dio: ^5.7.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_local_notifications: ^18.0.1
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  flutter_qiblah: ^3.0.3
  flutter_svg: ^2.0.10+1
  flutter_tts: ^4.0.2
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  geolocator: ^11.1.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  jhijri: ^1.0.0
  just_audio_background: ^0.0.1-beta.13
  modal_progress_hud_nsn: ^0.5.1
  package_info_plus: ^8.0.1
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  provider: ^6.0.1
  quran: ^1.0.7
  recase: ^4.0.0
  share_plus: ^10.0.2
  shared_preferences: ^2.0.8
  shimmer: ^3.0.0
  sqflite: ^2.3.3+2
  synchronized: ^3.3.0+3
  timezone: ^0.10.0
  url_launcher: ^6.0.12
  url_strategy: ^0.3.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/azkar.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/db/adhkar.json
    - assets/db/ruqiya.json
    - assets/quranjson/juz.json
    - assets/quranjson/surah/
    - assets/quranjson/translation/ar/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Regular.ttf
    - family: DiodrumArabic
      fonts:
        - asset: assets/fonts/alfont_com_AlFont_com_DiodrumArabic-Regular-1.ttf
flutter_assets:
  assets_path: assets/images
  output_path: lib/utils/
  filename: app_images.dart
  field_prefix: null

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
